export const commoditiesList = [
  "Tomato and Pepper",
  "Poultry and Eggs",
  "Bananas and Plantains",
  "Oil Palm and Coconut",
  "Rice",
  "Beef",
  "Melons",
  "Soybeans, Nuts and Meals",
  "Maize and Maize Oil",
  "Lamb and Ram",
  "Apples and Grapes",
  "Rapeseed and Mustard Oil",
  "Sorghum",
  "Pork",
  "Citrus Fruits",
  "Sunflower and Cottonseed Oils",
  "Potatoes",
  "Pulses",
  "Mangoes, Guavas and Mangosteens",
  "Groundnut and Sesame Oils",
  "Yam and Cassava",
  "Milk",
  "Pineapples",
  "Fish",
  "Wheat and Sugar",
  "Cephalopods and Shellfish"
];
